apiVersion: v1
description: DEPRECATED - Apache Superset (incubating) is a modern, enterprise-ready business intelligence web application
name: superset
version: 1.1.13
appVersion: "0.36.0"
keywords:
- bi
home: https://github.com/raziel130889/superset
icon: https://github.com/raziel130889/superset/blob/master/superset-frontend/images/superset-logo-horiz.png
sources:
- https://github.com/raziel130889/superset
deprecated: False